### ISSUE TITLE
Very narrow settings window

### ISSUE THREAD

**Issue by vishae** [ebullient/obsidian-snippetor#20]
The settings window for Snippetor is very narrow, which makes it very hard to make changes (I can't even see the preview icon).

No matter how wide my monitor is - and I tried this with the ultra-wide monitor at work, the snippetor settings window doesn't resize.

Can you help?

![image](https://user-images.githubusercontent.com/6110232/232976007-705fbc78-cab4-4b9a-9b75-66cc0da245dc.png)

**Comment by ebullient** [comment]
yes.. let me have a look. What you're seeing should not be happening, but it's possible that CSS coming from obsidian has changed. Thanks for opening the issue.

**Comment by vishae** [comment]
Thanks for making that change.
Just letting you know that with the new update, when a new custom checkbox snippet is created, the checkboxes are all missing the checks

<img width="44" alt="image" src="https://user-images.githubusercontent.com/6110232/233226974-b816500a-062a-445d-8b8b-3cd4ad8fbbc1.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6110232/233227126-14d6827b-901f-47a3-830b-34c10355a3ad.png">

**Comment by ebullient** [comment]
let me double check.. thanks!

**Comment by vishae** [comment]
hey again,

I think the fix only fixed Reading view and not Live Preview view.

**Comment by ebullient** [comment]
Try again? =)

**Comment by vishae** [comment]
yep, all good now, thanks!
