### ISSUE TITLE
Support customizing uncompleted tasks

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-snippetor#3]
To make uncompleted tasks stand out from a list of tasks with different statuses, it would be great if one can also customize the style of uncompleted tasks, e.g. changing their background color. Similarly, would it also be possible to support setting background colors for other statuses of tasks?

**Comment by ebullient** [comment]
Background is coming... uh.. in 2 seconds. ;)

**Comment by wenlzhang** [comment]
This is great!

I tried to apply background color to uncompleted tasks as follows. However, the background color cannot be previewed in the configuration pane, i.e. the text "example" does not have a background color. Also, with this setting, the generated snippet would render uncompleted tasks with a check mark in Live Preview; it would show correctly in Reading View, though.
<img width="898" alt="Screenshot 2022-01-23 at 12 03 57" src="https://user-images.githubusercontent.com/44930227/150675510-7268550e-76dc-458f-a139-08b5a65c0b3a.png">

**Comment by ebullient** [comment]
> This is great!
> 
> 
> 
> I tried to apply background color to uncompleted tasks as follows. However, the background color cannot be previewed in the configuration pane, i.e. the text "example" does not have a background color. Also, with this setting, the generated snippet would render uncompleted tasks with a check mark in Live Preview; it would show correctly in Reading View, though.
> 
> <img width="898" alt="Screenshot 2022-01-23 at 12 03 57" src="https://user-images.githubusercontent.com/44930227/150675510-7268550e-76dc-458f-a139-08b5a65c0b3a.png">
> 
> 

Is that the minimal theme? California coast (off the top of my head) does something that hides the checkboxes in list items. Try flipping to the default theme to make sure all of the inline checkboxes appear (so that you can toggle the background on and off).  

I have to do something a little different to style incomplete tasks. That will come next (and will resolve this issue). I just happened to have the general support for background tasks almost done when you asked. ;)

**Comment by ebullient** [comment]
Also, please update to 0.1.5.. there are a few fixes. ;) BRAT should help keep you up to date.

**Comment by wenlzhang** [comment]
> Is that the minimal theme? California coast (off the top of my head) does something that hides the checkboxes in list items. Try flipping to the default theme to make sure all of the inline checkboxes appear (so that you can toggle the background on and off).

Yes, that's the Minimal theme.

Now I am testing the Snippetor version 0.1.5 with the Obsidian default theme, and the background color setting works nicely for cancelled tasks. Hopefully this would also be updated for uncompleted tasks. :-)

A minor issue is that is it possible to remove the background color of the checkbox part in Live Preview? This can be seen for cancelled tasks.

<img width="1023" alt="Screenshot 2022-01-23 at 14 15 00" src="https://user-images.githubusercontent.com/44930227/150680418-9eedd84f-c0e0-48bd-b6aa-e04070f02936.png">

Reading View:
<img width="595" alt="Screenshot 2022-01-23 at 14 27 15" src="https://user-images.githubusercontent.com/44930227/150680755-ee99c21a-1f71-42e3-8537-6d0e900ffb18.png">

Live Preview:
<img width="775" alt="Screenshot 2022-01-23 at 14 27 08" src="https://user-images.githubusercontent.com/44930227/150680758-782cca61-5e63-4ba3-a5b6-4e773b95b720.png">

**Comment by ebullient** [comment]
I'll try. Open a separate issue for live preview rendering?

**Comment by ebullient** [comment]
Resolved by [`77cb356`](https://github.com/ebullient/obsidian-snippetor/commit/77cb3562d8f9ff34f0c6cc1b419bef97310a1d1e), which is in [0.1.6](https://github.com/ebullient/obsidian-snippetor/releases/tag/0.1.6)
