### ISSUE TITLE
[Bug/Issue] Text Background Colours are not rendered 

### ISSUE THREAD

**Issue by dummifiedme** [ebullient/obsidian-snippetor#6]
Will start with the screenshots:

**Settings**

![image](https://user-images.githubusercontent.com/68785729/152078535-3df90cc3-1850-4cb7-86e7-d1c25700ef8a.png)

**The Note**

SANCTUM THEME: (Live Preview — Reading Mode)
![image](https://user-images.githubusercontent.com/68785729/152078704-2842177c-0c02-416c-bcc2-462194f84a3f.png)

DEFAULT THEME: (Live Preview — Reading Mode)
![image](https://user-images.githubusercontent.com/68785729/152078781-affb172e-8228-4cb0-a843-099998bdf11c.png)

EDIT: So, I tried to change the colours manually and this happened :D
![image](https://user-images.githubusercontent.com/68785729/152080617-f90854af-341e-44dd-9b29-02e63c3462bf.png)

I manually changed the variable to a colour 'red' and important tags (ALthought, I tried again, and it works without the important tag as well :))

![image](https://user-images.githubusercontent.com/68785729/152080698-93dd7eec-1d92-4639-8553-6ada574a9695.png)

**Comment by dummifiedme** [comment]
Okay, so I found the culprit!

I have two snippets. I thought I would have different snippets for different kinds of task admonition so as to disable some whenever I want to.

So, I guess it ends up with two admonitions with the same variable `(--snippetor-li-1)` which makes it ambiguous.
Turning the other snippet off fixes the issue.

But I hope, this can be fixed. 
Maybe use UUID kind of a random variable names :D (You know better)

**Comment by ebullient** [comment]
Yes.. I was kind of thinking one snippet at a time.. I could use the snippet name instead of snippetor?

**Comment by dummifiedme** [comment]
> Yes.. I was kind of thinking one snippet at a time.. I could use the snippet name instead of snippetor?

Yeah, that makes more sense.
