### ISSUE TITLE
Doesn't work with dataview task view

### ISSUE THREAD

**Issue by imeed166** [ebullient/obsidian-snippetor#9]
Add support for dataview taks view. The custom checkboxes revert to the default look in the query.

https://user-images.githubusercontent.com/38974541/154637279-1a308643-dbdf-4755-9c55-9dc979be9452.mov

**Comment by ebullient** [comment]
This will be resolved by https://github.com/blacksmithgu/obsidian-dataview/pull/1047, when that is released.

Dataview tasks were not previously aligned (attributes, etc) with other task lists.
